[package]
name = "controverse-cir3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4"
rocket_contrib = { version = "0.4", features = ["handlebars_templates"] }
serde = { version = "1.0", features = ["derive"] }
